title: "Blog | isaak.dev"
description: Thoughts about software development.

author: Isaak Uchakaev
email: likid.geimfari@gmail.com
username: likid_geimfari
twitter_url: https://twitter.com/likid_geimfari
github_url: https://github.com/lk-geimfari
telegram_url: https://t.me/likid_geimfari

disqus_id: isaak-dev-1
google_analytics_id: UA-170154050-1

baseurl: ""
url: "https://isaak.dev"
rss_url: "https://isaak.dev/feed.xml"
github_edit_url: "https://github.com/lk-geimfari/lk-geimfari.github.io/blob/master"
default_preview_image: https://isaak.dev/assets/images/other/preview.png

include: [_pages]
markdown: kramdown
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
permalink: /:year/:month/:title

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
