title: "Isaak's Blog"
description: Thoughts about software development.

author: Isaak Uchakaev
email: likid.geimfari@gmail.com
username: likid_geimfari
twitter_url: https://twitter.com/likid_geimfari
github_url: https://github.com/lk-geimfari
telegram_url: https://t.me/likid_geimfari

wallets:
  btc: "1Eg75hne97eU55VQPMVh8BE8qHxPicLYKF"
  eth: "0xc305b8cd8169448ce624df6c83462d599998e3ab"
  xmr: "882GVN7iowS2YJbt6Lt9HaLE5oSn7RXaPdXY8rURkx5FL6PM8jfa367MEExUFULfHX9C9zVFVGN4qbavfdRxfFYtRKEqTb3"

google_analytics_id: UA-170154050-1

baseurl: ""
url: "https://isaak.dev"
rss_url: "https://isaak.dev/feed.xml"
github_edit_url: "https://github.com/lk-geimfari/lk-geimfari.github.io/edit/master"
default_preview_image: https://isaak.dev/assets/images/other/preview.png

projects:
  mimesis: "https://github.com/lk-geimfari/mimesis"
  awesomo: "https://github.com/lk-geimfari/awesomo"
  secrets: "https://github.com/lk-geimfari/secrets.clj"
  nebula: "https://github.com/lk-geimfari/nebula"
  mimety: "https://github.com/lk-geimfari/mimety"
  expynent: "https://github.com/lk-geimfari/expynent"
  mimesis_factory: "https://github.com/lk-geimfari/mimesis-factory"
  pytest_mimesis: "https://github.com/pytest-dev/pytest-mimesis"
  censortracker: "https://github.com/roskomsvoboda/censortracker"

resume:
  ru: "https://isaak.dev/assets/files/Исаак_Учакаев_-_Backend_Engineer.pdf"
  en: "https://isaak.dev/assets/files/Isaak_Uchakaev_-_Backend_Engineer.pdf"

pgp:
  key: "https://keys.openpgp.org/vks/v1/by-fingerprint/43D7CF7ABD04B9178443CF8A778A732D7666A23A"
  fingerprint: "43D7 CF7A BD04 B917 8443 CF8A 778A 732D 7666 A23A"

include: [_pages]
markdown: kramdown
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
permalink: /:year/:month/:title

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
